cluster.name: "xyz-es"

node.name: "${HOST}-data"
node.master:  false
node.data:    true
node.ingest:  false

network.host: "0.0.0.0"
http.port:          ${PORT_HTTP}
transport.tcp.port: ${PORT_TRANSPORT}

path.data: "/es-data"
path.logs: "/es-data/logs"

discovery.zen.hosts_provider: file

#memory
bootstrap.memory_lock: true
indices.fielddata.cache.size: 20%

#index
thread_pool.bulk.queue_size: 3000

action.destructive_requires_name: true