cluster.name: "${ES_CLUSTER_NAME}"

node.name: "${HOST}-master"
node.master:  true
node.data:    false
node.ingest:  false

network.host: "0.0.0.0"
http.port:          ${PORT_HTTP}
transport.tcp.port: ${PORT_TRANSPORT}

path.data: "/es-data"
path.logs: "/es-data/logs"

discovery.zen.hosts_provider: file
discovery.zen.minimum_master_nodes: 1

#memory
indices.fielddata.cache.size: 20%

#index
thread_pool.bulk.queue_size: 3000

action.destructive_requires_name: true
